export const ADD_SHIPPING_DETAILS = 'ADD_SHIPPING_DETAILS'

export const ADD_PAYMENT_DETAILS = 'ADD_PAYMENT_DETAILS'

export const VIEW_ORDERS = 'VIEW_ORDERS'

export const CLEAR_ORDER = 'CLEAR_ORDER'